import { Box, Typography } from '@mui/material'
import { Container } from '@mui/system'
import type { NextPage } from 'next'
import Head from 'next/head'
import MainPage from '../components/MainPage'
import styles from '../styles/Home.module.css'

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Tic-Tac-Toe</title>
        <meta name="Tic-Tac-Toe Game" content="Generated by create next app" />
        <link rel="icon" href="/hashtag-solid.svg" />
      </Head>

      <main>
        <Container maxWidth="xl">
          <MainPage/>
        </Container>
      </main>

      <footer className={styles.footer}>
        <Box>
          <Typography>Created exclusively by Sean Brent</Typography>
        </Box>
      </footer>
    </div>
  );
}

export default Home
